# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install:
  - brew update
  - gem install cocoapods -v '= 0.35.0'
  - cd Example && pod install && cd -
script:
  - xctool build-tests -workspace Example/CVKInfoBanner.xcworkspace -scheme CVKInfoBanner -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool run-tests -workspace Example/CVKInfoBanner.xcworkspace -scheme CVKInfoBanner -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "platform=iOS Simulator,name=iPhone 5s,OS=latest"
  - xctool run-tests -workspace Example/CVKInfoBanner.xcworkspace -scheme CVKInfoBanner -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "platform=iOS Simulator,name=iPhone 6,OS=latest"
  - xctool run-tests -workspace Example/CVKInfoBanner.xcworkspace -scheme CVKInfoBanner -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "platform=iOS Simulator,name=iPhone 6 Plus,OS=latest"
